apiVersion: apps/v1
kind: Deployment
metadata:
  name: interviewhub-deployment
  namespace: "2401054"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interviewhub
  template:
    metadata:
      labels:
        app: interviewhub
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: interviewhub
          image: 127.0.0.1:30085/2401054/interviewhub:v1
          ports:
            - containerPort: 3000
          env:
            - name: STREAM_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STREAM_SECRET_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLERK_SECRET_KEY
