apiVersion: apps/v1
kind: Deployment
metadata:
  name: interviewhub-deployment
  namespace: 2401054
  labels:
    app: interviewhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interviewhub
  template:
    metadata:
      labels:
        app: interviewhub
    spec:
      containers:
        - name: interviewhub-container
          image: nexus-service.nexus.svc.cluster.local:8085/2401054/interviewhub:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: interviewhub-secret
            - configMapRef:
                name: interviewhub-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      restartPolicy: Always
