apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: interviewhub-ingress
  namespace: "2401054"
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: interviewhub-2401054.imcc.com   # Your app domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: interviewhub-service   # Your service name
                port:
                  number: 80
