apiVersion: v1
kind: Service
metadata:
  name: interviewhub-service
  namespace: 2401054
  labels:
    app: interviewhub
spec:
  type: NodePort
  selector:
    app: interviewhub
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000    # URL: http://NODE-IP:31000
