apiVersion: v1
kind: Service
metadata:
  name: interviewhub-service
  namespace: "2401054"
  labels:
    app: interviewhub
spec:
  type: NodePort
  selector:
    app: interviewhub
  ports:
    - protocol: TCP
      port: 3000        # Service port
      targetPort: 3000  # Container port
      nodePort: 31000   # NodePort (for browser access)
